package com.farmaaishrestaurant.service;

import com.farmaaishrestaurant.dto.EventDto;
import com.farmaaishrestaurant.exception.ResourceNotFoundException;
import com.farmaaishrestaurant.model.Event;
import com.farmaaishrestaurant.repository.EventRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class EventService {

    private final EventRepository eventRepository;

    public EventService(EventRepository eventRepository) {
        this.eventRepository = eventRepository;
    }

    public EventDto createEvent(EventDto eventDto) {
        if (eventDto == null || eventDto.getTitle() == null || eventDto.getTitle().isEmpty() ||
            eventDto.getImageUrl() == null || eventDto.getImageUrl().isEmpty() ||
            eventDto.getEventType() == null || eventDto.getEventType().isEmpty()) {
            throw new IllegalArgumentException("EventDto, title, imageUrl, and eventType cannot be null or empty.");
        }

        Event event = convertToEntity(eventDto);
        event.setId(null); // Ensure ID is generated by DB
        Event savedEvent = eventRepository.save(event);
        return convertToDto(savedEvent);
    }

    public EventDto getEventById(UUID id) {
        Event event = eventRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Event not found with id: " + id));
        return convertToDto(event);
    }

    public List<EventDto> getAllEvents() {
        return eventRepository.findAll().stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }

    public List<EventDto> getActiveEvents() {
        return eventRepository.findByActiveTrue().stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }

    public List<EventDto> getEventsByType(String eventType) {
        return eventRepository.findByEventTypeAndActiveTrue(eventType).stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }

    public EventDto updateEvent(UUID id, EventDto eventDto) {
        if (!eventRepository.existsById(id)) {
            throw new ResourceNotFoundException("Event not found with id: " + id);
        }
        if (eventDto == null || eventDto.getTitle() == null || eventDto.getTitle().isEmpty() ||
            eventDto.getImageUrl() == null || eventDto.getImageUrl().isEmpty() ||
            eventDto.getEventType() == null || eventDto.getEventType().isEmpty()) {
            throw new IllegalArgumentException("EventDto, title, imageUrl, and eventType cannot be null or empty.");
        }

        Event event = convertToEntity(eventDto);
        event.setId(id); // Set the ID for update
        Event updatedEvent = eventRepository.save(event);
        return convertToDto(updatedEvent);
    }

    public void deleteEvent(UUID id) {
        if (!eventRepository.existsById(id)) {
            throw new ResourceNotFoundException("Event not found with id: " + id);
        }
        eventRepository.deleteById(id);
    }

    private EventDto convertToDto(Event event) {
        return EventDto.builder()
                .id(event.getId())
                .title(event.getTitle())
                .description(event.getDescription())
                .imageUrl(event.getImageUrl())
                .eventDate(event.getEventDate())
                .eventType(event.getEventType())
                .active(event.isActive())
                .build();
    }

    private Event convertToEntity(EventDto eventDto) {
        Event event = new Event();
        event.setId(eventDto.getId());
        event.setTitle(eventDto.getTitle());
        event.setDescription(eventDto.getDescription());
        event.setImageUrl(eventDto.getImageUrl());
        event.setEventDate(eventDto.getEventDate());
        event.setEventType(eventDto.getEventType());
        event.setActive(eventDto.getActive() != null ? eventDto.getActive() : false); // Default to false if null
        return event;
    }
}