package com.farmaaishrestaurant.service;

import com.farmaaishrestaurant.dto.PostDto;
import com.farmaaishrestaurant.exception.ResourceNotFoundException;
import com.farmaaishrestaurant.model.Post;
import com.farmaaishrestaurant.repository.PostRepository;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class PostService {

    private final PostRepository postRepository;

    public PostService(PostRepository postRepository) {
        this.postRepository = postRepository;
    }

    public List<PostDto> getAllPosts() {
        List<Post> posts = postRepository.findAll(Sort.by(Sort.Direction.DESC, "publishDate"));
        return posts.stream().map(this::convertToDto).collect(Collectors.toList());
    }

    public PostDto getPostById(UUID id) {
        Post post = postRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Post not found with id: " + id));
        return convertToDto(post);
    }

    public PostDto createPost(PostDto postDto) {
        Post post = convertToEntity(postDto);
        post.setId(null); // Ensure ID is generated by the system
        post.setPublishDate(LocalDate.now()); // Set publish date to now
        Post savedPost = postRepository.save(post);
        return convertToDto(savedPost);
    }

    public PostDto updatePost(UUID id, PostDto postDto) {
        Post existingPost = postRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Post not found with id: " + id));

        existingPost.setTitle(postDto.getTitle());
        existingPost.setContent(postDto.getContent());
        existingPost.setAuthor(postDto.getAuthor());
        existingPost.setImageUrl(postDto.getImageUrl());
        // publishDate is not updated on purpose as per common blog update logic

        Post updatedPost = postRepository.save(existingPost);
        return convertToDto(updatedPost);
    }

    public void deletePost(UUID id) {
        if (!postRepository.existsById(id)) {
            throw new ResourceNotFoundException("Post not found with id: " + id);
        }
        postRepository.deleteById(id);
    }

    private PostDto convertToDto(Post post) {
        return PostDto.builder()
                .id(post.getId())
                .title(post.getTitle())
                .content(post.getContent())
                .author(post.getAuthor())
                .publishDate(post.getPublishDate())
                .imageUrl(post.getImageUrl())
                .build();
    }

    private Post convertToEntity(PostDto postDto) {
        Post post = new Post();
        post.setId(postDto.getId()); // ID might be null for new posts, will be generated
        post.setTitle(postDto.getTitle());
        post.setContent(postDto.getContent());
        post.setAuthor(postDto.getAuthor());
        post.setPublishDate(postDto.getPublishDate() != null ? postDto.getPublishDate() : LocalDate.now());
        post.setImageUrl(postDto.getImageUrl());
        return post;
    }
}