package com.farmaaishrestaurant.service;

import com.farmaaishrestaurant.dto.ReviewDto;
import com.farmaaishrestaurant.exception.ResourceNotFoundException;
import com.farmaaishrestaurant.model.Review;
import com.farmaaishrestaurant.repository.ReviewRepository;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class ReviewService {

    private final ReviewRepository reviewRepository;

    public ReviewService(ReviewRepository reviewRepository) {
        this.reviewRepository = reviewRepository;
    }

    public List<ReviewDto> getFeaturedReviews() {
        return reviewRepository.findByIsFeatured(true).stream()
                .map(this::mapToDto)
                .collect(Collectors.toList());
    }

    public List<ReviewDto> getAllReviews() {
        return reviewRepository.findAll().stream()
                .map(this::mapToDto)
                .collect(Collectors.toList());
    }

    public ReviewDto getReviewById(UUID id) {
        Review review = reviewRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Review not found with id: " + id));
        return mapToDto(review);
    }

    public ReviewDto createReview(ReviewDto reviewDto) {
        Review review = mapToEntity(reviewDto);
        review.setCreatedAt(LocalDateTime.now());
        review.setUpdatedAt(LocalDateTime.now());
        Review savedReview = reviewRepository.save(review);
        return mapToDto(savedReview);
    }

    public ReviewDto updateReview(UUID id, ReviewDto reviewDto) {
        Review existingReview = reviewRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Review not found with id: " + id));

        existingReview.setAuthorName(reviewDto.getAuthorName());
        existingReview.setRating(reviewDto.getRating());
        existingReview.setComment(reviewDto.getComment());
        existingReview.setSource(reviewDto.getSource());
        existingReview.setReviewDate(reviewDto.getReviewDate());
        existingReview.setIsFeatured(reviewDto.getIsFeatured());
        existingReview.setUpdatedAt(LocalDateTime.now());

        Review updatedReview = reviewRepository.save(existingReview);
        return mapToDto(updatedReview);
    }

    public void deleteReview(UUID id) {
        if (!reviewRepository.existsById(id)) {
            throw new ResourceNotFoundException("Review not found with id: " + id);
        }
        reviewRepository.deleteById(id);
    }

    public void syncReviewsFromGoogle() {
        System.out.println("Simulating sync reviews from Google Business Profile...");
        // In a real implementation, this would involve calling an external API
        // to fetch new reviews and update existing ones in the database.
        // It should handle potential duplicates based on `externalId`.
    }

    private ReviewDto mapToDto(Review review) {
        return ReviewDto.builder()
                .id(review.getId())
                .authorName(review.getAuthorName())
                .rating(review.getRating())
                .comment(review.getComment())
                .source(review.getSource())
                .reviewDate(review.getReviewDate())
                .isFeatured(review.getIsFeatured())
                .build();
    }

    private Review mapToEntity(ReviewDto reviewDto) {
        Review review = new Review();
        review.setId(reviewDto.getId()); // ID might be null for new reviews, will be generated by JPA
        review.setAuthorName(reviewDto.getAuthorName());
        review.setRating(reviewDto.getRating());
        review.setComment(reviewDto.getComment());
        review.setSource(reviewDto.getSource());
        review.setReviewDate(reviewDto.getReviewDate());
        review.setIsFeatured(reviewDto.getIsFeatured() != null ? reviewDto.getIsFeatured() : false);
        return review;
    }
}